### PR TITLE
remove references to the "private" field of channel info returned from listpeers RPC

### LINKED ISSUE #192: plugin-clboss: Unexpected listpeers
I recently upgraded to 24.02 and started experiencing the following issues. I see this error on both NodeBalanceSwapper and EarningsRebalancer. I updated to CLN 24.02.1 and I'm seeing the same result. (I'm running the release-v0.13.1 branch of CLBOSS)

The output suggests unexpected output from listpeers:

lnplay-cln-0_cln-0.1.qd0bv3uuhtpm@librem-mini    | Unhandled exception in concurrent task!
lnplay-cln-0_cln-0.1.qd0bv3uuhtpm@librem-mini    | Incorrect type.
lnplay-cln-0_cln-0.1.qd0bv3uuhtpm@librem-mini    | ...main loop continuing...
lnplay-cln-0_cln-0.1.qd0bv3uuhtpm@librem-mini    | 2024-04-06T15:05:51.312Z **BROKEN** plugin-clboss: NodeBalanceSwapper: Unexpected listpeers: [\n\t{\n\t\t\"id\" : \"03e30da473716d39c09356d5372cf839d8ee3a1cdbd993ee853c23ab9bdfbce6f8\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"211.23.128.57:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03d6f092d9806c189d8fe2475d8a31260e891a861f57c10d742e08c02412767d5e\",\n\t\t\"connected\" : false,\n\t\t\"num_channels\" : 1,\n\t\t\"features\" : \"\"\n\t},\n\t{\n\t\t\"id\" : \"03979d66fa2be1741a92c56707d8b7c0c48d9565ad526f7ce3706202d2250c4218\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"5xzvqwv4mcfj5nnoacm54272ooykvohu3x7jfebpbqlss4a2ozz7i3yd.onion:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"118.163.74.161:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:25103\",\n\t\t\"features\" : \"08a0000a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"027833211bdc28059b323492f2e51453559a2fcbaf947c16f716d060e560128eb2\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"10.10.0.2:43300\"\n\t\t],\n\t\t\"features\" : \"08a0800a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"031a33566a118aca7d71c37386fca49004c247810fc4a1dc7c08c2eb982b3c5215\",\n\t\t\"connected\" : false,\n\t\t\"num_channels\" : 1,\n\t\t\"features\" : \"\"\n\t},\n\t{\n\t\t\"id\" : \"0370fb1bb00afce3d161a71e4b71ed19891f9b4d5ff8c7cba83239bc556641fcb5\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"7athpxle7bgig4to7xllsmgz6vx6t3r3xnnjg6fhtwfugtpeclyo53id.onion:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"034f3f792988c43f41c65a839acdfa48647204bb99aca7de426f7c80b0dcf7a4a6\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"vbya6gvgslwxjc3bulmvlhukyrl42uzbogwi3qu2uad7eed5nu6oxlqd.onion:9735\"\n\t\t],\n\t\t\"features\" : \"80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008a000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"02fe6a27ddcb2dd9fa8479fe1d52549b5932079a493b51f1409fa2c5878f1bc07c\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"65.108.134.61:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:5396\",\n\t\t\"features\" : \"08a0002a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"02d96eadea3d780104449aca5c93461ce67c1564e2e1d73225fa67dd3b997a6018\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"45.86.229.190:9736\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:60267\",\n\t\t\"features\" : \"08a0000a8a5961\"\n\t},\n\t{\n\t\t\"id\" : \"0399d8b8817ef2623e1bce5ba14727a804b2643dc79c5f352408c67bf18e7ab38a\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"4rwjdl7wyt5sgou2sptr3ahakf7geagyptroaors2frbfjfravp726id.onion:9735\"\n\t\t],\n\t\t\"features\" : \"80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008a000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"174.169.193.33:9735\"\n\t\t],\n\t\t\"features\" : \"08a0000a8a59a1\"\n\t},\n\t{\n\t\t\"id\" : \"021f98b9898720f8633c93faf0aa54ab399d277464e502d1111b233c2cf4064828\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"155.248.202.151:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:20491\",\n\t\t\"features\" : \"08a0000a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"029ca15ad2ea3077f5f0524c4c9bc266854c14b9fc81b9cc3d6b48e2460af13f65\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"141.95.84.44:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:14576\",\n\t\t\"features\" : \"08a0000a8a59a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a5886df676f3b3216a4520156157b8d653e262b520281d8d325c24fd8b456b9c\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"188.165.2.4:9737\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03c8dfbf829eaeb0b6dab099d87fdf7f8faceb0c1b935cd243e8c1fb5af71361cf\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"3.234.251.85:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a41f7069f0398d2b91351b8b35b3348de23919810589719aaab1c9458a2d3542\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"10.10.0.2:44140\"\n\t\t],\n\t\t\"features\" : \"0000000000000000\"\n\t}\n]
lnplay-cln-0_cln-0.1.qd0bv3uuhtpm@librem-mini    | 2024-04-06T15:05:51.314Z **BROKEN** plugin-clboss: EarningsRebalancer: Unexpected result from listpeers: [\n\t{\n\t\t\"id\" : \"03e30da473716d39c09356d5372cf839d8ee3a1cdbd993ee853c23ab9bdfbce6f8\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"211.23.128.57:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03d6f092d9806c189d8fe2475d8a31260e891a861f57c10d742e08c02412767d5e\",\n\t\t\"connected\" : false,\n\t\t\"num_channels\" : 1,\n\t\t\"features\" : \"\"\n\t},\n\t{\n\t\t\"id\" : \"03979d66fa2be1741a92c56707d8b7c0c48d9565ad526f7ce3706202d2250c4218\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"5xzvqwv4mcfj5nnoacm54272ooykvohu3x7jfebpbqlss4a2ozz7i3yd.onion:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"118.163.74.161:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:25103\",\n\t\t\"features\" : \"08a0000a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"027833211bdc28059b323492f2e51453559a2fcbaf947c16f716d060e560128eb2\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"10.10.0.2:43300\"\n\t\t],\n\t\t\"features\" : \"08a0800a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"031a33566a118aca7d71c37386fca49004c247810fc4a1dc7c08c2eb982b3c5215\",\n\t\t\"connected\" : false,\n\t\t\"num_channels\" : 1,\n\t\t\"features\" : \"\"\n\t},\n\t{\n\t\t\"id\" : \"0370fb1bb00afce3d161a71e4b71ed19891f9b4d5ff8c7cba83239bc556641fcb5\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"7athpxle7bgig4to7xllsmgz6vx6t3r3xnnjg6fhtwfugtpeclyo53id.onion:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"034f3f792988c43f41c65a839acdfa48647204bb99aca7de426f7c80b0dcf7a4a6\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"vbya6gvgslwxjc3bulmvlhukyrl42uzbogwi3qu2uad7eed5nu6oxlqd.onion:9735\"\n\t\t],\n\t\t\"features\" : \"80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008a000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"02fe6a27ddcb2dd9fa8479fe1d52549b5932079a493b51f1409fa2c5878f1bc07c\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"65.108.134.61:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:5396\",\n\t\t\"features\" : \"08a0002a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"02d96eadea3d780104449aca5c93461ce67c1564e2e1d73225fa67dd3b997a6018\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"45.86.229.190:9736\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:60267\",\n\t\t\"features\" : \"08a0000a8a5961\"\n\t},\n\t{\n\t\t\"id\" : \"0399d8b8817ef2623e1bce5ba14727a804b2643dc79c5f352408c67bf18e7ab38a\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"4rwjdl7wyt5sgou2sptr3ahakf7geagyptroaors2frbfjfravp726id.onion:9735\"\n\t\t],\n\t\t\"features\" : \"80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008a000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"174.169.193.33:9735\"\n\t\t],\n\t\t\"features\" : \"08a0000a8a59a1\"\n\t},\n\t{\n\t\t\"id\" : \"021f98b9898720f8633c93faf0aa54ab399d277464e502d1111b233c2cf4064828\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"155.248.202.151:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:20491\",\n\t\t\"features\" : \"08a0000a0a69a2\"\n\t},\n\t{\n\t\t\"id\" : \"029ca15ad2ea3077f5f0524c4c9bc266854c14b9fc81b9cc3d6b48e2460af13f65\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"141.95.84.44:9735\"\n\t\t],\n\t\t\"remote_addr\" : \"99.184.79.163:14576\",\n\t\t\"features\" : \"08a0000a8a59a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a5886df676f3b3216a4520156157b8d653e262b520281d8d325c24fd8b456b9c\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"188.165.2.4:9737\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888252a1\"\n\t},\n\t{\n\t\t\"id\" : \"03c8dfbf829eaeb0b6dab099d87fdf7f8faceb0c1b935cd243e8c1fb5af71361cf\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 1,\n\t\t\"netaddr\" : [\n\t\t\t\"3.234.251.85:9735\"\n\t\t],\n\t\t\"features\" : \"800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000888a52a1\"\n\t},\n\t{\n\t\t\"id\" : \"03a41f7069f0398d2b91351b8b35b3348de23919810589719aaab1c9458a2d3542\",\n\t\t\"connected\" : true,\n\t\t\"num_channels\" : 0,\n\t\t\"netaddr\" : [\n\t\t\t\"10.10.0.2:44140\"\n\t\t],\n\t\t\"features\" : \"0000000000000000\"\n\t}\n]

### PR DESCRIPTION
**Pull request by ksedgwic**
Maybe fixes https://github.com/ZmnSCPxj/clboss/issues/192

The private field has been removed because the private channels are no longer supposed to show up in the list:
https://github.com/ElementsProject/lightning/commit/37ccca5d69c38adbbbceb81e2e18b9699b6cd53c

Since we were always checking private to skip the channel it seems safe to simply not check for it anymore ...

### CODE REVIEW

**Comment by ksedgwic** [comment]
@vincenzopalazzo if you get a chance could you look this change over?

File: tests/boss/test_initialrebalancer.cpp [hunk 1]
```diff
@@ -53,17 +53,15 @@ class DummyEarningsManager {
  */
```
Comment (vincenzopalazzo) [inline tests/boss/test_initialrebalancer.cpp:53]: Maybe this PR is a good way to remind us that listpeerchannels is now a way to iterate over all the channels?

File: Boss/Mod/InitialRebalancer.cpp [hunk 2]
```diff
@@ -182,11 +182,6 @@ class InitialRebalancer::Impl::Run::Impl
 
 					auto cs = p["channels"];
```
Comment (vincenzopalazzo) [inline Boss/Mod/InitialRebalancer.cpp:183]: if a user run `deprecated-api = false`, this object is null

from cln docs of listpeers: `channels (array of objects, optional) deprecated in v23.02, removed after v24.02`

File: Boss/Mod/EarningsRebalancer.cpp [hunk 3]
```diff
@@ -157,11 +157,6 @@ class EarningsRebalancer::Impl {
 				));
 
 				for (auto c : p["channels"]) {
```
Comment (vincenzopalazzo) [inline Boss/Mod/EarningsRebalancer.cpp:159]: same here I guess

**Review by vincenzopalazzo — COMMENTED** [review]
I think there are two issue: one is the one that you fixed, and the one is the one where the `channels` no longer lives inside the `listpeers` command

**Comment by ksedgwic** [comment]
@vincenzopalazzo should we add the `listpeerchannels` fixes to this PR or make a follow-on PR to switch to `listpeerchannels`?

**Comment by vincenzopalazzo** [comment]
Now sure @ksedgwic we can do this in multiple PR?

**Comment by ksedgwic** [comment]
>  Now sure @ksedgwic we can do this in multiple PR?

I'm not sure if you are asking or answering ... if this PR is safe (won't break anything in any circumstance) and effective (doesn't crash when there is no `private` field then we should merge it and do more PRs.

But I'm not confident I understand when the `private` field will be missing:
1. it certainly is not missing much of the time, I think because the RPC interface still inserts it when the channel is not announced?
2. I don't know if we will see actual private channels in some circumstances (ie, with allow deprecated flag) in which case it might be bad to remove the skip when we see a private channel check

It feel like with both https://github.com/ZmnSCPxj/clboss/issues and https://github.com/ElementsProject/lightning/issues/7197 we are mostly not missing the private field and then occasionally in special circumstances it is missing.

**Comment by vincenzopalazzo** [comment]
>I'm not sure if you are asking or answering ...

Oh sorry :) for me ether way it is fine, we should just remember to migrate at some point!

and you are right I think your pr is fixing the crash and you be ok to merge imho

**Review by vincenzopalazzo — APPROVED** [review]
ACK  https://github.com/ZmnSCPxj/clboss/pull/193/commits/2f09bce175f8a3cb9808cb4384b245a68f48fd14

Sounds solid to me, thanks for doing it
